### ISSUE TITLE
Figures for comparing the different sites

### ISSUE THREAD

**Issue by aammd** [SrivastavaLab/bwg_drought_data_comparison#1]
@dsrivast , I managed to work out a simple example of what I was talking about earlier today! These reports are automatically generated from the same template. See the markdown files in the `report` directory for examples. Right now it compares only the four measures of "bromeliad size", but we could extend this to anything!

**Comment by dsrivast** [comment]
Wow, Andrew, you have taken this to another level. Looks awesome.

Can I suggest the next two variable combinations building on what you have
done:

chemical variables final
ecosystem measures (decomp, fpom, 15N, %N, CO2, methane, bacteria)

and then one of the things we'll get everyone to check is the total final
abundance all aquatic inverts in the three random bromeliads, the total #
terrestrials seen in those 3 bromeliads.

Diane

## 

Diane Srivastava
Professor
Dept of Zoology & Biodiversity Research Centre,
University of British Columbia
6270 University Blvd
Vancouver BC Canada V6T 1Z4
604-822-1350 (no voicemail)

**Comment by aammd** [comment]
Sounds good! Perhaps a simgle report could have 6 sections:
- bromeliad size
- chemical (initial)
- chemical (final)
- ecosystem
- inverts (aquatic)
- inverts (terrestrial)

Each section could have a pairs figure and three random plants to validate

Should it be the same three plants in all sections?

**Comment by dsrivast** [comment]
I think it would be easiest if it was the same 3 plants.

It would be easiest if the 3 plant validations were all together in one
pdf per site that we could print off...just because I don't trust the
wifi...

## 

Diane Srivastava
Professor
Dept of Zoology & Biodiversity Research Centre,
University of British Columbia
6270 University Blvd
Vancouver BC Canada V6T 1Z4
604-822-1350 (no voicemail)

**Comment by aammd** [comment]
Hi @dsrivast 
FYI I just updated these. there are two relevant changes:
- the "check" documents now refer to the same plants in all tables (previously it was different bromeliads in both the aquatic and terrestrial insect categories)
- the data comparisons now contain more figures for ecosystem functions and final chemistry.

Not sure if you have printed these yet; if not let me know if there is anything else I can do.

**Comment by dsrivast** [comment]
## thanks @aamd! Havent printed yet, but will tonight!

Diane Srivastava
Professor
Dept of Zoology & Biodiversity Research Centre,
University of British Columbia
6270 University Blvd
Vancouver BC Canada V6T 1Z4
604-822-1350 (no voicemail)
